# Generated by Django 5.2.4 on 2025-07-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "trip_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("interests", models.TextField(blank=True)),
                ("num_people", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("completed", "已完成"),
                            ("failed", "生成失败"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="auth_app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TripBudget",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="budget",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripFood",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="food",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripHotel",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="hotel",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripItinerary",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="itinerary",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripSummary",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="summary",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripTransport",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="transport",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TripWeather",
            fields=[
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="weather",
                        serialize=False,
                        to="trip.trip",
                    ),
                ),
                ("markdown_content", models.TextField()),
            ],
        ),
    ]
